name: Auto Merge PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Auto Merge PR
      uses: pascalgn/automerge-action@v0.14.3
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
